### ISSUE TITLE
Very slow loading when there are many tasks

### ISSUE THREAD

**Issue by ystyle** [varbhat/exatorrent#143]
There may be more than ten or twenty tasks

![2021-12-15_01-51-15](https://user-images.githubusercontent.com/4478635/146053112-e6bd7511-f7dd-4ff3-b651-df3d3530375e.gif)

**Comment by ystyle** [comment]
It may take a few minutes to load

**Comment by varbhat** [comment]
@ystyle ,i agree with what you said and i have known it. the reason why it happens is because of lack of pagination.

Currently all data that needs to be sent is parsed after all the data is received. When the size of data/load is increased, naturally it takes more time to load everything.

I had initially considered streaming json or to implement pagination (it would have really helped since exatorrent uses websocket). I will really consider this issue.

also, if you have any suggestions,feel free to discuss.

**Comment by ystyle** [comment]
You can save the metadata information to the database first, and then go to get the download progress information after loading the list

**Comment by varbhat** [comment]
@ystyle , that's what i also am doing currently. i plan to improve RPC of exatorrent in some time in future.

also, current implementation just loads every torrent, converts to json and sends it to client,so that's the issue.
