### ISSUE TITLE
Different folder per user

### ISSUE THREAD

**Issue by JamesDAdams** [varbhat/exatorrent#251]
Hi, 

it's possible to add a functionality to config a specific download folder for each user ?

Example : 
![image](https://user-images.githubusercontent.com/20860324/169886238-92200c25-c595-47d6-a4bc-ee824b2f7300.png)

![image](https://user-images.githubusercontent.com/20860324/169886191-2ea3a75b-4b48-45d1-bf33-27b5f4526128.png)

Thanks.

**Comment by varbhat** [comment]
Sorry, @JamesDAdams . I intentionally didn't add this feature.  Thus, you can't change the user download directory. 
Programmatically, I could have done it but i didn't because:
1) i wanted exatorrent to operate under only one directory (exadir)
2) have exatorrent get information about torrents by directly polling the directory.
