### ISSUE TITLE
Running `./exatorrent -engc -torc` keeps client running

### ISSUE THREAD

**Issue by flying-sausages** [varbhat/exatorrent#26]
I'd like to create all configs in the `exadir`, have exa quit, and then edit the config manually. Running the two flags together will keep the client running instead of it quitting after writing the confs.

```
root@swiz:/tmp# /opt/exatorrent/exatorrent -engc -torc

Address => :5000
Directory => exadir

[INFO] 2021/08/28 11:52:23 Torrent Client Configuration is now loaded from  exadir/config/clientconfig.json
[INFO] 2021/08/28 11:52:23 Engine Configuration {DisableLocalCache:false OnlineCacheURL:https://itorrents.org/torrent/%s.torrent TrackerRefresh:60 TrackerListURLs:[https://ngosang.github.io/trackerslist/trackers_best.txt] DisAllowTrackersUser:false DisAllowTrackersCache:false GlobalSeedRatio:0 SRRefresh:150 DontRemoveCacheInfo:false LockbyDefault:false} is now loaded
[INFO] 2021/08/28 11:52:23 Torrent Client Created
[INFO] 2021/08/28 11:52:23 Starting server on :5000
[INFO] 2021/08/28 11:52:23 Loaded  20  trackers from  https://ngosang.github.io/trackerslist/trackers_best.txt
[INFO] 2021/08/28 11:52:23 Loaded  20  trackers in total , eliminating duplicates
[INFO] 2021/08/28 11:52:23 Added Loaded Trackers to Torrents
```

**Comment by varbhat** [comment]
@flying-sausages ,

When those configuration files are ALREADY present, it just loads them and will not exit to allow you to edit.

If the Configuration file/s is not present and you have passed the flag , it will create sample configuration file and WILL EXIT to allow you to edit.


By looking at the log you have sent , configuration files are already present before you have run and thus exatorrent loaded those configuration and didn't stop.
I think this is not first time you are running (since exadir is already populated with sample configuration file). Please delete those configuration, and restart with flags. It MUST definitely exit to allow you edit those configuration files.

I am closing this issue as this is not issue.

**Comment by varbhat** [comment]
Also @flying-sausages ,

Better not run exatorrent with root permissions (as root user)

**Comment by flying-sausages** [comment]
> Also @flying-sausages ,
> 
> Better not run exatorrent with root permissions (as root user)

No worries, this is just a quick throw-away VM for playing around ;)

> When those configuration files are ALREADY present, it just loads them and will not exit to allow you to edit.

Oh ok, good to know. I would argue that's somewhat an unexpected outcome. I would assume this would _always_ overwrite the file and then die. Anyhow, I'll at least add it to the docs in a PR when I'm done piling things together.

**Comment by varbhat** [comment]
@flying-sausages ,
I think that i have mentioned all of these in usage section.

**Comment by flying-sausages** [comment]
https://github.com/varbhat/exatorrent/blob/main/docs/usage.md#-engc I mean the options are noted there, but there's not much written on the behaviour if the file exists.

**Comment by varbhat** [comment]
@flying-sausages ,

I am working on revamping some of docs. will correct it soon :)
