### ISSUE TITLE
Feature request: Watch a directory for .torrent files

### ISSUE THREAD

**Issue by benpro** [varbhat/exatorrent#50]
And automatically add them and start downloading.

**Comment by varbhat** [comment]
@benpro ,

I had thought of this feature during development but INTENTIONALLY didn't implement it because it gets complex in multi-user scenarios (like which user must own the torrent , will it be limited to admins only? , etc.). This is also why i didn't implement "Addition of Torrents based on RSS feed" 

BUT ,

I would like this to be implemented as seperate Program which utilizes exatorrent API . A seperate daemon which takes Username+Password , watches over the directory, automatically adds new Torrents whenever they are added to the directory would be cool. But, i would like this to be seperate program. You are also welcome to contribute towards this.

I may implement this addon in near future.

I am closing this issue for now, If you have any issues, please re-open.

**Comment by benpro** [comment]
Can I use the API to say, start this torrent in /tmp/foo.bar.torrent?

**Comment by varbhat** [comment]
What do you mean by start?

Do you mean adding the torrent by Torrent file ? 

If yes, then you can add by Torrent.
Please see https://github.com/varbhat/exatorrent/blob/593a0a9b6b7d7349a362c531742725415169702d/internal/core/socket.go#L475

```json
{
  "command": "addtorrent",
  "data1": "base64encodedtorrentfile",
  "data2": "true or false",
}
```

if you want torrent not to be started on Add, send true in data2 otherwise false(or don't include data2)
